import { useState, useCallback, useRef } from "react";

const API_URL = "http://127.0.0.1:8000/predict";

export default function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef();
  const barRef = useRef();

  const handleFile = (f) => {
    if (!f || !f.type.startsWith("image/")) return;
    setFile(f);
    setPreview(URL.createObjectURL(f));
    setResult(null);
    setError(null);
  };

  const onDrop = useCallback((e) => {
    e.preventDefault();
    setDragging(false);
    handleFile(e.dataTransfer.files[0]);
  }, []);

  const detect = async () => {
    if (!file) return;
    setLoading(true);
    setResult(null);
    setError(null);

    const form = new FormData();
    form.append("file", file);

    try {
      const res = await fetch(API_URL, { method: "POST", body: form });
      if (!res.ok) throw new Error(`Server error ${res.status}`);
      const data = await res.json();
      setResult(data);
      // Animate bar after render
      setTimeout(() => {
        if (barRef.current) {
          barRef.current.style.width = Math.round((data.confidence ?? 0.5) * 100) + "%";
        }
      }, 50);
    } catch (err) {
      setError(err.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  const isFake = result && result.prediction?.toLowerCase() === "fake";
  const conf = result ? Math.round((result.confidence ?? 0.5) * 100) : 0;

  return (
    <div style={styles.page}>
      <div style={styles.gridBg} />
      <div style={styles.blob} />

      <div style={styles.wrap}>
        {/* Header */}
        <header style={styles.header}>
          <div style={styles.eyebrow}>Detection Engine</div>
          <h1 style={styles.h1}>AI Image Detector</h1>
          <p style={styles.sub}>
            Upload any image to analyze whether it was generated by AI or captured by a camera.
          </p>
        </header>

        {/* Card */}
        <div style={styles.card}>
          <div style={styles.cardTopLine} />

          {/* Drop Zone or Preview */}
          {!preview ? (
            <div
              style={{
                ...styles.drop,
                ...(dragging ? styles.dropHover : {}),
              }}
              onClick={() => inputRef.current.click()}
              onDragEnter={(e) => { e.preventDefault(); setDragging(true); }}
              onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={onDrop}
            >
              <div style={styles.dropIcon}>
                <svg width="22" height="22" fill="none" stroke="#6C8EFF" strokeWidth="1.5" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5"/>
                </svg>
              </div>
              <p style={styles.dropText}>
                <strong style={{ color: "#e2e4f0" }}>Drop your image here</strong>
                <br />
                or <span style={styles.browse}>browse to upload</span>
              </p>
              <span style={styles.formats}>PNG · JPG · WEBP · BMP</span>
            </div>
          ) : (
            <div style={styles.previewWrap}>
              <img src={preview} alt="Preview" style={styles.previewImg} />
              <button style={styles.changeBtn} onClick={() => inputRef.current.click()}>
                ↺ Change
              </button>
            </div>
          )}

          <input
            ref={inputRef}
            type="file"
            accept="image/*"
            style={{ display: "none" }}
            onChange={(e) => handleFile(e.target.files[0])}
          />

          {/* Detect Button */}
          <button
            style={{ ...styles.detectBtn, opacity: !file || loading ? 0.4 : 1 }}
            disabled={!file || loading}
            onClick={detect}
          >
            {loading ? (
              <>
                <span style={styles.spinner} /> Analyzing…
              </>
            ) : (
              <>
                <svg width="15" height="15" fill="none" stroke="white" strokeWidth="2" viewBox="0 0 24 24" style={{ verticalAlign: "middle", marginRight: 6 }}>
                  <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
                </svg>
                Detect
              </>
            )}
          </button>

          {/* Error */}
          {error && <div style={styles.errBox}>⚠ {error}</div>}

          {/* Result */}
          {result && (
            <div style={{ ...styles.resultBox, ...(isFake ? styles.resultFake : styles.resultReal) }}>
              <div style={isFake ? styles.resultTopFake : styles.resultTopReal} />
              <div style={styles.resultHdr}>
                <div style={{ ...styles.badge, background: isFake ? "rgba(248,113,113,.15)" : "rgba(52,211,153,.15)" }}>
                  {isFake ? "🤖" : "📷"}
                </div>
                <div>
                  <div style={{ ...styles.verdict, color: isFake ? "#f87171" : "#34d399" }}>
                    {isFake ? "AI-Generated" : "Authentic Photo"}
                  </div>
                  <div style={styles.verdictSub}>VERDICT</div>
                </div>
              </div>

              {/* Confidence */}
              <div style={styles.confRow}>
                <span style={styles.confLabel}>Confidence</span>
                <span style={{ ...styles.confVal, color: isFake ? "#f87171" : "#34d399" }}>{conf}%</span>
              </div>
              <div style={styles.barTrack}>
                <div
                  ref={barRef}
                  style={{
                    ...styles.barFill,
                    width: "0%",
                    background: isFake
                      ? "linear-gradient(90deg,#b91c1c,#f87171)"
                      : "linear-gradient(90deg,#059669,#34d399)",
                  }}
                />
              </div>

              {/* Sub-scores */}
              {result.scores && Object.keys(result.scores).length > 0 && (
                <div style={styles.scoresGrid}>
                  {Object.entries(result.scores).map(([key, val]) => (
                    <div key={key} style={styles.chip}>
                      <div style={styles.chipLabel}>{key}</div>
                      <div style={styles.chipVal}>{Math.round(val * 100)}%</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        <div style={styles.footer}>Powered by FastAPI · Results are probabilistic</div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    background: "#07090f",
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    fontFamily: "'Syne', sans-serif",
    color: "#e2e4f0",
    position: "relative",
    overflow: "hidden",
  },
  gridBg: {
    position: "fixed", inset: 0,
    backgroundImage: "linear-gradient(rgba(108,142,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(108,142,255,.03) 1px,transparent 1px)",
    backgroundSize: "48px 48px",
    pointerEvents: "none", zIndex: 0,
  },
  blob: {
    position: "fixed", top: "-20%", left: "50%", transform: "translateX(-50%)",
    width: 600, height: 400,
    background: "radial-gradient(ellipse,rgba(108,142,255,.1) 0%,transparent 70%)",
    pointerEvents: "none", zIndex: 0,
  },
  wrap: { position: "relative", zIndex: 1, width: "100%", maxWidth: 520 },
  header: { textAlign: "center", marginBottom: 28 },
  eyebrow: {
    fontFamily: "monospace", fontSize: 10, letterSpacing: "0.2em",
    textTransform: "uppercase", color: "#6C8EFF", marginBottom: 10,
  },
  h1: {
    fontSize: "clamp(26px,6vw,36px)", fontWeight: 800, letterSpacing: "-0.03em",
    margin: "0 0 8px",
    background: "linear-gradient(135deg,#e2e4f0,#9ba8ff,#67e8f9)",
    WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text",
  },
  sub: { fontSize: 13, color: "#5a5e7a", margin: 0, lineHeight: 1.7 },
  card: {
    background: "#0e1018", border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: 18, padding: 28, display: "flex", flexDirection: "column",
    gap: 18, position: "relative", overflow: "hidden",
  },
  cardTopLine: {
    position: "absolute", top: 0, left: 0, right: 0, height: 1,
    background: "linear-gradient(90deg,transparent,rgba(108,142,255,.4),transparent)",
  },
  drop: {
    border: "2px dashed rgba(255,255,255,0.07)", borderRadius: 12,
    background: "#13151f", padding: "36px 20px", textAlign: "center",
    cursor: "pointer", transition: ".2s",
  },
  dropHover: {
    borderColor: "rgba(108,142,255,.5)",
    background: "rgba(108,142,255,.08)",
  },
  dropIcon: {
    width: 48, height: 48, background: "rgba(108,142,255,.12)", borderRadius: 12,
    display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 14px",
  },
  dropText: { fontSize: 14, color: "#5a5e7a", margin: 0, lineHeight: 1.7 },
  browse: { color: "#6C8EFF", fontWeight: 600, cursor: "pointer" },
  formats: {
    display: "block", marginTop: 6,
    fontFamily: "monospace", fontSize: 10, letterSpacing: ".1em",
    color: "rgba(90,94,122,.5)",
  },
  previewWrap: { position: "relative", borderRadius: 12, overflow: "hidden", background: "#000" },
  previewImg: { display: "block", width: "100%", maxHeight: 280, objectFit: "contain" },
  changeBtn: {
    position: "absolute", bottom: 10, right: 10,
    background: "rgba(7,9,15,.85)", border: "1px solid rgba(255,255,255,0.07)",
    color: "#e2e4f0", fontFamily: "monospace", fontSize: 11, padding: "5px 12px",
    borderRadius: 8, cursor: "pointer", backdropFilter: "blur(8px)",
  },
  detectBtn: {
    width: "100%", padding: "15px", background: "#6C8EFF", color: "#fff",
    border: "none", borderRadius: 12, fontFamily: "'Syne',sans-serif",
    fontSize: 15, fontWeight: 700, letterSpacing: ".04em", cursor: "pointer",
    transition: ".2s", display: "flex", alignItems: "center", justifyContent: "center",
  },
  spinner: {
    display: "inline-block", width: 15, height: 15, marginRight: 6,
    border: "2px solid rgba(255,255,255,.3)", borderTopColor: "#fff",
    borderRadius: "50%", animation: "spin .7s linear infinite",
  },
  errBox: {
    background: "rgba(248,113,113,.07)", border: "1px solid rgba(248,113,113,.2)",
    borderRadius: 10, padding: "14px 16px", fontFamily: "monospace",
    fontSize: 12, color: "#fca5a5",
  },
  resultBox: { borderRadius: 12, padding: 22, position: "relative", overflow: "hidden" },
  resultReal: { background: "rgba(52,211,153,.07)", border: "1px solid rgba(52,211,153,.25)" },
  resultFake: { background: "rgba(248,113,113,.07)", border: "1px solid rgba(248,113,113,.25)" },
  resultTopReal: { position:"absolute",top:0,left:0,right:0,height:2,background:"linear-gradient(90deg,transparent,#34d399,transparent)" },
  resultTopFake: { position:"absolute",top:0,left:0,right:0,height:2,background:"linear-gradient(90deg,transparent,#f87171,transparent)" },
  resultHdr: { display: "flex", alignItems: "center", gap: 12, marginBottom: 18 },
  badge: { width: 42, height: 42, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 },
  verdict: { fontSize: 18, fontWeight: 800, letterSpacing: "-0.02em" },
  verdictSub: { fontFamily: "monospace", fontSize: 10, color: "#5a5e7a", letterSpacing: ".12em", marginTop: 2 },
  confRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  confLabel: { fontFamily: "monospace", fontSize: 10, color: "#5a5e7a", letterSpacing: ".12em", textTransform: "uppercase" },
  confVal: { fontFamily: "monospace", fontSize: 20, fontWeight: 500 },
  barTrack: { height: 5, background: "rgba(255,255,255,.06)", borderRadius: 99, overflow: "hidden" },
  barFill: { height: "100%", borderRadius: 99, width: "0%", transition: "width 1s cubic-bezier(.16,1,.3,1)" },
  scoresGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 9, marginTop: 14 },
  chip: { background: "rgba(255,255,255,.04)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 9, padding: "10px 12px" },
  chipLabel: { fontFamily: "monospace", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "#5a5e7a", marginBottom: 3 },
  chipVal: { fontFamily: "monospace", fontSize: 15, fontWeight: 500, color: "#e2e4f0" },
  footer: { textAlign: "center", marginTop: 14, fontFamily: "monospace", fontSize: 10, color: "rgba(90,94,122,.4)", letterSpacing: ".08em" },
};